### Theory – NumPy Project (BMW Global Sales Data Analysis)
1. Data Loading and Libraries

In this project, two Python libraries are used:

Pandas – used for reading CSV files and handling tabular data (DataFrames).
NumPy – used for numerical operations and array processing.

Theory:
Pandas is mainly used for data manipulation and cleaning, while NumPy is used for mathematical and statistical operations on numerical data using arrays.

In [ ]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("bmw_global_sales_2018_2025.csv")

In [3]:
df.head(10)

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.50,1.00
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.50,1.00
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.50,1.00
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.50,1.00
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.50,1.00
5,2018,1,Europe,i4,10607,64082,679717774,0.035,19.12,3.50,1.00
6,2018,1,Europe,iX,4805,73975,355449875,0.016,19.12,3.50,1.00
7,2018,1,Europe,MINI,2554,43005,109834770,0.013,19.12,3.50,1.00
8,2018,1,China,3 Series,3826,48068,183908168,0.021,17.60,2.37,1.02
9,2018,1,China,5 Series,7498,62435,468137630,0.015,17.60,2.37,1.02

In [35]:
df.describe()

,Year,Month,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
count,3072.000000,3072.000000,3072.000000,3072.000000,3.072000e+03,3072.000000,3072.000000,3072.000000,3072.000000
mean,2021.500000,6.500000,7980.288086,63854.561523,5.113995e+08,0.107572,14.660234,3.057526,1.176224
std,2.291661,3.452615,3174.917444,14655.891299,2.431185e+08,0.058099,5.334604,1.018103,0.118123
min,2018.000000,1.000000,2379.000000,40011.000000,1.045314e+08,-0.015000,5.090000,0.100000,0.920000
25%,2019.750000,3.750000,5225.500000,54500.250000,3.125504e+08,0.057000,12.275000,2.370000,1.080000
50%,2021.500000,6.500000,7985.500000,63493.000000,4.808690e+08,0.108000,16.260000,3.060000,1.180000
75%,2023.250000,9.250000,10528.250000,71489.500000,6.709141e+08,0.157250,18.932500,3.852500,1.270000
max,2025.000000,12.000000,15914.000000,93994.000000,1.433482e+09,0.223000,20.970000,5.820000,1.410000

In [36]:
df.tail()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
3067,2025,12,RestOfWorld,X5,9281,68198,632945638,0.201,5.89,2.37,1.41
3068,2025,12,RestOfWorld,X7,12785,91839,1174161615,0.203,5.89,2.37,1.41
3069,2025,12,RestOfWorld,i4,4906,63437,311221922,0.180,5.89,2.37,1.41
3070,2025,12,RestOfWorld,iX,7871,73867,581407157,0.196,5.89,2.37,1.41
3071,2025,12,RestOfWorld,MINI,6732,41811,281471652,0.167,5.89,2.37,1.41

In [12]:
df.isnull().sum()

Year                0
Month               0
Region              0
Model               0
Units_Sold          0
Avg_Price_EUR       0
Revenue_EUR         0
BEV_Share           0
Premium_Share       0
GDP_Growth          0
Fuel_Price_Index    0
dtype: int64

In [13]:
df.columns

Index(['Year', 'Month', 'Region', 'Model', 'Units_Sold', 'Avg_Price_EUR',
       'Revenue_EUR', 'BEV_Share', 'Premium_Share', 'GDP_Growth',
       'Fuel_Price_Index'],
      dtype='str')

#### Convert to numpy array

In [ ]:
units = np.array(df["Units_Sold"])
price = np.array(df["Avg_Price_EUR"])
revenue = np.array(df["Revenue_EUR"])
gdp = np.array(df["GDP_Growth"])
fuel = np.array(df["Fuel_Price_Index"])

### Data Exploration

In [18]:
print("Total Records:", units.size)
print("Average Units Sold:", np.mean(units))
print("Maximum Units Sold:", np.max(units))
print("Minimum Units Sold:", np.min(units))

Total Records: 3072
Average Units Sold: 7980.2880859375
Maximum Units Sold: 15914
Minimum Units Sold: 2379

### Revenue Analysis

In [22]:
print("Total Revenue:", np.sum(revenue))
print("Average Revenue:", np.mean(revenue))
print("Revenue Standard Deviation:", np.std(revenue))

Total Revenue: 1571019298118
Average Revenue: 511399511.1061198
Revenue Standard Deviation: 243078952.68253803

### Price Analysis

In [23]:
print("Average Car Price:", np.mean(price))
print("Highest Price:", np.max(price))
print("Lowest Price:", np.min(price))

Average Car Price: 63854.5615234375
Highest Price: 93994
Lowest Price: 40011

### sorting

In [24]:
sorted_units = np.sort(units)
print("Sorted Units Sold:", sorted_units)

Sorted Units Sold: [ 2379  2427  2455 ... 15533 15877 15914]

In [25]:
top_sales = np.sort(units)[-5:]
print("Top 5 Sales:", top_sales)

Top 5 Sales: [15448 15528 15533 15877 15914]